### ISSUE TITLE
Gulp Inject Error

### ISSUE THREAD

**Issue by umair321** [zwacky/angular-flippy#13]
I am installing angular-flippy with "bower install angular-flippy --save" (just like all other modules) but after "gulp serve" it doesn't include in my index file (All bower modules are just there except this one).

**Comment by zwacky** [comment]
i never tested with bower. maybe bower.json links to a wrong version (since it has 2.0.0) and we fixed it in 2.0.1.

**Comment by zwacky** [comment]
just updated the bower.json. can you retest it? please watch out, that bower isn't using a cached version.
or do it directly via `bower install angular-flipp#2.0.1 --save`. does that work?

**Comment by Jaichand** [comment]
No, it's not working.

it's not able to link the script like this
 <script type="text/javascript" src="../bower_components/angular-flippy/dist/js/angular-flippy.min.js"></script>

In the directory of angular-flippy
angular-flippy > demo >index.html having this :
<script type="text/javascript" src="../node_modules/angular/angular.js"></script>

But in my node_modules, I am not having this Directory. 

when I use it with bower, then it should be(I think) like this:
angular-flippy > demo >index.html
<script type="text/javascript" src="../bower_components/angular/angular.js"></script>

**Comment by WDShannon** [comment]
I'm having this issue too, there are two files in the angular-flippy folder --- .bower.json and bower.json.  One has the version set to 2.0.1 and the other at 2.0.0.  MY bower.json has the correct  version at 2.0.1.

**Comment by zwacky** [comment]
there shouldn't be a `.bower.json` in the angular-flippy folder as there shouldn't be any resolutions and such.

i assume you guys use _wiredep_ to inject css and js files into html. i'll try to reproduce this.

**Comment by zwacky** [comment]
i realized that the main files don't match the files in the dist folder. thanks for pointing out, will fix that!

**Comment by zwacky** [comment]
fixed
