### ISSUE TITLE
Custom Method for flippy with unique id

### ISSUE THREAD

**Issue by isaacrlevin** [zwacky/angular-flippy#25]
I am trying to implement the flippy directive in an ng-repeat like so

https://drive.google.com/open?id=0BxB-19VLAr8STWdIWjF1MjBsaEk

I want to display a list of flippys and that is working as expected. I also want to be able to flip each flippy independently of eachother, and I am guessing I can do that with custom events somehow. I have a Save button in each flippy like above that calls a method that taps into broadcast

`vm.saveObjective = function (id) {
            $rootScope.$broadcast(id);
            return "";
        }`

The issue I am running into is that flippy runs before the browser is populated, which makes the code in the flippy directive just get the variable name instead of the variable value when it ties up the event. Without modifying the directive, is there a way to do what I want?

**Comment by zwacky** [comment]
try

```
flip-back="['custom:' + objective.Id]"
```

**Comment by isaacrlevin** [comment]
That did the trick! Way too easy :)
