### ISSUE TITLE
Flippy element height

### ISSUE THREAD

**Issue by adyba** [zwacky/angular-flippy#26]
Simon, 
I have potentially the same problem described here #4 but I believe it should be addressed separately. 
The problem is that the Flippy element has zero/inherited height once rendered.  All the content is overflowing. It works fine once there is only one <flippy> in an empty fix height div or body. In more dynamic environment the next HTML element is hidden behind the topmost current flippy content (z-index change had no effect).
The only solution I was able to figure out in one day was to measure the `front` and `back` real height and force directive (link function) to propagate those numbers (height of the content) to the parent div. 
Is there a any better (more CSS) solution?

**Comment by zwacky** [comment]
hey @adyba, I can't say I fully understand.
Dou you maybe have a codepen/plunkr/xyz for me to look at?

**Comment by adyba** [comment]
Well my solution works only for Ionic. I'm (ab)using $ionicView.enter event that is fired after all the DOM of the controller is properly rendered so I don't have the good solution for a "naked" Angular. 

To describe the problem I did my best to draw a picture to explain it.
![flippy](https://cloud.githubusercontent.com/assets/6436599/21391368/b6ebab12-c78b-11e6-82f1-9e68df06f417.png)
The dark blue rectangle is your `<flippy>` element that has inherit (in reality ZERO) height.
It's content `<flippy-front>` and `<flippy-back>` overflows the `<flippy>` and does all the magic.

Unfortunately any further content (the red rectangle) is displayed just after the `<flippy>` and thus possibly hidden behind the overflowing content. Once you know the real height of the content (front&back) there is no issue. But once the content is dynamic you are in trouble.

I believe there must be a CSS solution (clearfix, clear:both) but all my attempts failed. I'm anything but no CSS expert so I have used  oldschool JS.

**Comment by zwacky** [comment]
I still didn't understand your issue completely 😓. If you could create a tiny codepen/plunkr/jsbin for just this case would help a lot.

**Comment by adyba** [comment]
Just put a `<div id=" style="border: red 3px solid;">Can you see me?</div>` just after the `</flippy>` in you **jsbin** example and you will find what I mean. Once the width of the output viewport is narrow like on mobile, the content of `flippy` covers the red div completely.

**Comment by zwacky** [comment]
you mean like http://jsbin.com/fusoyizuya/1/edit?html,js,output ?

In that case, you could put the `display: inline-block;` style and it won't be overlapped by flippy itself.
Did I understand the issue now?

**Comment by zwacky** [comment]
closed due to no response by issuer.
