### ISSUE TITLE
Multiple Flippie's on page they overlap

### ISSUE THREAD

**Issue by lorneb** [zwacky/angular-flippy#4]
Hi was just giving your fine work a test drive, and found that
If you put more then one on a page they all stack on top of each other.

**Comment by 360disrupt** [comment]
Only the last one flips the others don't flip anymore.

**Comment by joydeep1982** [comment]
exactly only the last element flips and nothing else flips ....

**Comment by zwacky** [comment]
will tackle this with next release

**Comment by mackclark** [comment]
@lorneb  I had the same problem and as an interim fix I gave each flippy (except the first one) a left-margin of the width of the flippy. This stops them from overlapping, and lets you click/hover them all to flip. I also had success with giving them all a fixed width instead of the margin-left.

**Comment by kaushikgandhi** [comment]
@zwacky :(

**Comment by zwacky** [comment]
this should be fixed with v2.0.
if something is off, please feel free to reopen the issue.
sorry for the long wait.
