### ISSUE TITLE
Flip effect does not work on Internet Explorer 11

### ISSUE THREAD

**Issue by fpernia** [zwacky/angular-flippy#5]
Hi, I'm trying to using your flip effect, but when I test it with internet explorer 11.0.21 the effect is not completed.

I attach a print screen

![flip](https://cloud.githubusercontent.com/assets/12814610/10590048/7b9344fe-7678-11e5-8ab8-bd450793418d.png)

**Comment by mackclark** [comment]
Yeah I am having the same problem, and it's not working in edge either. I noticed that it does seem to work in ie if you switch the rotation from the y to the x axis- as in:
 transform: rotate3d(1, 0, 0, -180deg);
I'm going to try and use that as a temporary fix for ie for now.

**Comment by zwacky** [comment]
hey can you check if this issue still remains with with the 2.0 version?

**Comment by mackclark** [comment]
It looks like it's not- I only checked your demo page though, is that up to date? I came up with a fix at work, I'll try to open a pull request when I get a chance.

**Comment by zwacky** [comment]
thanks for reporting back.
yeah please do so

**Comment by zwacky** [comment]
@mackclark hey mack, got around it? cheers

**Comment by zwacky** [comment]
we got a work around, sadly no 3d effect for now. (#17)
