### ISSUE TITLE
iOS behaviour broken

### ISSUE THREAD

**Issue by antidote2** [zwacky/angular-flippy#6]
Thanks for a nice effect, it's especially useful for responsive applications. As you can make lots of information available on small screen without overloading.

Though there is a strange behaviour I didn't investigate on iOS:

first touch: start flip and instantly return.
second touch: flip as expected
touch on any other "flip"-element: flip back previously flipped

**Comment by antidote2** [comment]
I've fixed this for myself  with:

 scope: {
 },
var isTouchDevice = 'ontouchstart' in document.documentElement;

```
                            $elem.click($scope.flip);
                            if(!isTouchDevice) {
                                $elem.mouseenter($scope.flip);
                                $elem.mouseleave($scope.flip);
                            }
```

**Comment by zwacky** [comment]
yeah you need to adjust it for touch devices, thanks for your hint.
